.TH "src/ansi.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ansi.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'Terminal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBnumValid\fP (std::string)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 8 of file ansi\&.cpp\&.
.SS "bool numValid (std::string)"

.PP
Definition at line 21 of file validation\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
