.TH "src/ansiArt/Ansi.txt" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ansiArt/Ansi.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "out \fBcolor\fP (37, 104)+'____________ ____ ___________' out\&.color(37"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "out ____ _ __ out _ out ____ out ___________ _____ _____ ______ out out out out _____ out out color (37, 104)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
