.TH "convert/colors.h" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
convert/colors.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBeyeString\fP (char cColor)"
.br
.ti -1c
.RI "string \fBhairString\fP (char cColor)"
.br
.ti -1c
.RI "string \fBrace\fP (int cRace)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string eyeString (char cColor)"

.PP
Definition at line 1 of file colors\&.h\&.
.SS "string hairString (char cColor)"

.PP
Definition at line 32 of file colors\&.h\&.
.SS "string race (int cRace)"

.PP
Definition at line 60 of file colors\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
