.TH "src/deletePerson.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/deletePerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Person\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP \fBselectPerson\fP ()"
.br
.ti -1c
.RI "int \fBdeletePerson\fP (std::string filename)"
.br
.RI "int deletePerson (std::string filename) takes a string that holdsthe name of a file to open\&. It opens the file and retrieves a selected \fBPerson\fP via selectPerson ()\&. It then deletes the entry from the file and truncates the file to correct length\&. It returns 0 on success and -1 on failure "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int deletePerson (std::string filename)"

.PP
int deletePerson (std::string filename) takes a string that holdsthe name of a file to open\&. It opens the file and retrieves a selected \fBPerson\fP via selectPerson ()\&. It then deletes the entry from the file and truncates the file to correct length\&. It returns 0 on success and -1 on failure 
.PP
Definition at line 13 of file deletePerson\&.cpp\&.
.SS "\fBPerson\fP selectPerson ()"

.PP
Definition at line 9 of file selectPerson\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
