.TH "src/editPerson.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/editPerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Person\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsavePerson\fP (\fBPerson\fP, std::string)"
.br
.ti -1c
.RI "\fBPerson\fP \fBselectPerson\fP ()"
.br
.ti -1c
.RI "bool \fBnameValid\fP (std::string)"
.br
.ti -1c
.RI "int \fBeditPerson\fP (std::string filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int editPerson (std::string filename)"

.PP
Definition at line 11 of file editPerson\&.cpp\&.
.SS "bool nameValid (std::string)"

.PP
Definition at line 5 of file validation\&.cpp\&.
.SS "int savePerson (\fBPerson\fP, std::string)"

.PP
Definition at line 9 of file savePerson\&.cpp\&.
.SS "\fBPerson\fP selectPerson ()"

.PP
Definition at line 9 of file selectPerson\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
