.TH "employeePay" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
employeePay
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBempNum\fP"
.br
.ti -1c
.RI "double \fBpayRate\fP"
.br
.ti -1c
.RI "double \fBhours\fP"
.br
.ti -1c
.RI "double \fBgrossPay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file employee\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int employeePay::empNum"

.PP
Definition at line 9 of file employee\&.cpp\&.
.SS "double employeePay::grossPay"

.PP
Definition at line 12 of file employee\&.cpp\&.
.SS "double employeePay::hours"

.PP
Definition at line 11 of file employee\&.cpp\&.
.SS "string employeePay::name"

.PP
Definition at line 8 of file employee\&.cpp\&.
.SS "double employeePay::payRate"

.PP
Definition at line 10 of file employee\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
