.TH "md__r_e_a_d_m_e" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- networkProjects - DOR 
Currently working on DOR - my personal Data OrganizeR 
.SH "Install"
.PP
No real installation yet, but we'll get there Found in the \fCsrc/\fP directory\&. Just type in \fCmake\fP
.PP
It should allow you to add in details about people, places, cars, and businesses\&. I'll be adding more soon\&. There is a lot to do, but if you want to help, feel free to email me at tpalmerstudios@gmail.com\&. I'm currently working on fixes for \fBsavePerson\&.cpp\fP, but I'll be moving on to \fBeditPerson\&.cpp\fP soon\&.
.PP
A simple conglomeration of random things I've worked on\&. Starting with some C and now C++\&. I've started with K&R\&. Now I'm using C++ by Tony Gaddis\&. 
.br
.PP
I'll try to actually update regularly now\&. And hopefully move on to bigger projects as I understand bigger concepts\&. 
