.TH "src/newPerson.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/newPerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Person\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsavePerson\fP (\fBPerson\fP, std::string)"
.br
.ti -1c
.RI "int \fBnewPerson\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int newPerson ()"

.PP
Definition at line 6 of file newPerson\&.cpp\&.
.SS "int savePerson (\fBPerson\fP, std::string)"

.PP
Definition at line 9 of file savePerson\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
