.TH "person" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
person
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "double \fBid\fP"
.br
.ti -1c
.RI "double \fBdob\fP"
.br
.ti -1c
.RI "double \fBdod\fP"
.br
.ti -1c
.RI "double \fBheight\fP"
.br
.ti -1c
.RI "double \fBweight\fP"
.br
.ti -1c
.RI "string \fBrace\fP"
.br
.ti -1c
.RI "string \fBhairColor\fP"
.br
.ti -1c
.RI "string \fBhairNotes\fP"
.br
.ti -1c
.RI "string \fBeyeColor\fP"
.br
.ti -1c
.RI "string \fBbodyMarks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file people\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "string person::bodyMarks"

.PP
Definition at line 20 of file people\&.cpp\&.
.SS "double person::dob"

.PP
Definition at line 12 of file people\&.cpp\&.
.SS "double person::dod"

.PP
Definition at line 13 of file people\&.cpp\&.
.SS "string person::eyeColor"

.PP
Definition at line 19 of file people\&.cpp\&.
.SS "string person::hairColor"

.PP
Definition at line 17 of file people\&.cpp\&.
.SS "string person::hairNotes"

.PP
Definition at line 18 of file people\&.cpp\&.
.SS "double person::height"

.PP
Definition at line 14 of file people\&.cpp\&.
.SS "double person::id"

.PP
Definition at line 11 of file people\&.cpp\&.
.SS "string person::name"

.PP
Definition at line 10 of file people\&.cpp\&.
.SS "string person::race"

.PP
Definition at line 16 of file people\&.cpp\&.
.SS "double person::weight"

.PP
Definition at line 15 of file people\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
