.TH "Person::Birth" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person::Birth
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Birth\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 1 of file Birth\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
