.TH "src/Person.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Person.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'Person\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
