.TH "src/Person.h" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Person.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPerson\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
