.TH "Person" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Person\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBirth\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP ()"
.br
.ti -1c
.RI "\fBPerson\fP (std::string saveString)"
.br
.ti -1c
.RI "void \fBtoPerson\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetFName\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetMName\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetLName\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetID\fP (std::string)"
.br
.ti -1c
.RI "void \fBoutPerson\fP ()"
.br
.ti -1c
.RI "void \fBsetID\fP (int)"
.br
.ti -1c
.RI "int \fBgetID\fP ()"
.br
.ti -1c
.RI "std::string \fBgetFName\fP ()"
.br
.ti -1c
.RI "std::string \fBgetMName\fP ()"
.br
.ti -1c
.RI "std::string \fBgetLName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Person\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Person::Person ()\fC [inline]\fP"

.PP
Definition at line 24 of file Person\&.h\&.
.SS "Person::Person (std::string saveString)\fC [inline]\fP"

.PP
Definition at line 33 of file Person\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Person::getFName ()\fC [inline]\fP"

.PP
Definition at line 82 of file Person\&.h\&.
.SS "int Person::getID ()\fC [inline]\fP"

.PP
Definition at line 76 of file Person\&.h\&.
.SS "std::string Person::getLName ()\fC [inline]\fP"

.PP
Definition at line 94 of file Person\&.h\&.
.SS "std::string Person::getMName ()\fC [inline]\fP"

.PP
Definition at line 88 of file Person\&.h\&.
.SS "void Person::outPerson ()"

.PP
Definition at line 80 of file Person\&.cpp\&.
.SS "void Person::setFName (std::string name)"
Sets the first name of \fBPerson\fP () 
.PP
\fBParameters\fP
.RS 4
\fIname\fP a string to be placed in the first name 
.RE
.PP

.PP
Definition at line 8 of file Person\&.cpp\&.
.SS "void Person::setID (int searchID)"

.PP
Definition at line 20 of file Person\&.cpp\&.
.SS "void Person::setID (std::string file)"
Sets the ID of a \fBPerson\fP () based on the last entry in a file Searches through a file for ID numbers and places a new ID on the final line 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP a filename to be searched for \fBPerson\fP entries 
.RE
.PP

.PP
Definition at line 25 of file Person\&.cpp\&.
.SS "void Person::setLName (std::string name)"
Sets the last name of \fBPerson\fP () 
.PP
\fBParameters\fP
.RS 4
\fIname\fP a string to be placed in the last name 
.RE
.PP

.PP
Definition at line 16 of file Person\&.cpp\&.
.SS "void Person::setMName (std::string name)"
Sets the middle name of \fBPerson\fP () 
.PP
\fBParameters\fP
.RS 4
\fIname\fP a string to be placed in the middle name 
.RE
.PP

.PP
Definition at line 12 of file Person\&.cpp\&.
.SS "void Person::toPerson (std::string saveString)"

.PP
Definition at line 57 of file Person\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
