.TH "Queue< queueStruct >" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queue< queueStruct >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructs\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueue\fP (int)"
.br
.ti -1c
.RI "\fBQueue\fP (const \fBQueue\fP &)"
.br
.ti -1c
.RI "\fB~Queue\fP ()"
.br
.ti -1c
.RI "void \fBenqueue\fP (queueStruct)"
.br
.ti -1c
.RI "void \fBdequeue\fP (queueStruct &)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "bool \fBisFull\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class queueStruct>
.br
class Queue< queueStruct >"

.PP
Definition at line 7 of file dataStructs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class queueStruct > \fBQueue\fP< queueStruct >::\fBQueue\fP (int size)"

.PP
Definition at line 31 of file dataStructs\&.h\&.
.SS "template<class queueStruct > \fBQueue\fP< queueStruct >::\fBQueue\fP (const \fBQueue\fP< queueStruct > & obj)"

.PP
Definition at line 44 of file dataStructs\&.h\&.
.SS "template<class queueStruct > \fBQueue\fP< queueStruct >::~\fBQueue\fP"

.PP
Definition at line 61 of file dataStructs\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class queueStruct > void \fBQueue\fP< queueStruct >::clear"

.PP
Definition at line 119 of file dataStructs\&.h\&.
.SS "template<class queueStruct > void \fBQueue\fP< queueStruct >::dequeue (queueStruct & item)"

.PP
Definition at line 82 of file dataStructs\&.h\&.
.SS "template<class queueStruct > void \fBQueue\fP< queueStruct >::enqueue (queueStruct item)"

.PP
Definition at line 69 of file dataStructs\&.h\&.
.SS "template<class queueStruct > bool \fBQueue\fP< queueStruct >::isEmpty"

.PP
Definition at line 95 of file dataStructs\&.h\&.
.SS "template<class queueStruct > bool \fBQueue\fP< queueStruct >::isFull"

.PP
Definition at line 107 of file dataStructs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
