.TH "src/savePerson.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/savePerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <regex>\fP
.br
\fC#include 'Person\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsavePerson\fP (\fBPerson\fP toSave, std::string filename)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPerson\fP \fBtoPerson\fP (std::string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int savePerson (\fBPerson\fP toSave, std::string filename)"

.PP
Definition at line 9 of file savePerson\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBPerson\fP toPerson(std::string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
