.TH "src/searchPerson.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/searchPerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Person\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP \fBIDtoPerson\fP (int)"
.br
.ti -1c
.RI "bool \fBsearchValid\fP (std::string)"
.br
.ti -1c
.RI "bool \fBnumValid\fP (std::string)"
.br
.ti -1c
.RI "\fBPerson\fP \fBsearchPerson\fP (std::string filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPerson\fP IDtoPerson (int)"

.PP
Definition at line 52 of file main\&.cpp\&.
.SS "bool numValid (std::string)"

.PP
Definition at line 21 of file validation\&.cpp\&.
.SS "\fBPerson\fP searchPerson (std::string filename)"

.PP
Definition at line 11 of file searchPerson\&.cpp\&.
.SS "bool searchValid (std::string)"

.PP
Definition at line 13 of file validation\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
