.TH "src/selectPerson.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/selectPerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Person\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP \fBIDtoPerson\fP (int)"
.br
.ti -1c
.RI "\fBPerson\fP \fBselectPerson\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPerson\fP \fBsearchPerson\fP (std::string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPerson\fP IDtoPerson (int)"

.PP
Definition at line 52 of file main\&.cpp\&.
.SS "\fBPerson\fP selectPerson ()"

.PP
Definition at line 9 of file selectPerson\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBPerson\fP searchPerson(std::string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
