.TH "Terminal" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terminal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Terminal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminal\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP (int x, int y)"
.br
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.ti -1c
.RI "void \fBsetSize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBclearscr\fP ()"
.br
.ti -1c
.RI "static std::string \fBgoLoc\fP (int x, int y)"
.br
.ti -1c
.RI "static std::string \fBunderline\fP ()"
.br
.ti -1c
.RI "static std::string \fBunderlineOff\fP ()"
.br
.ti -1c
.RI "static std::string \fBbold\fP ()"
.br
.ti -1c
.RI "static std::string \fBboldOff\fP ()"
.br
.ti -1c
.RI "static std::string \fBsave\fP ()"
.br
.ti -1c
.RI "static std::string \fBrestore\fP ()"
.br
.ti -1c
.RI "static std::string \fBup\fP (int y)"
.br
.ti -1c
.RI "static std::string \fBdown\fP (int y)"
.br
.ti -1c
.RI "static std::string \fBright\fP (int x)"
.br
.ti -1c
.RI "static std::string \fBleft\fP (int x)"
.br
.ti -1c
.RI "static std::string \fBcolor\fP (int colorbg, int colorfg)"
.br
.ti -1c
.RI "static std::string \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Terminal\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Terminal::Terminal ()\fC [inline]\fP"

.PP
Definition at line 15 of file Terminal\&.h\&.
.SS "Terminal::Terminal (int x, int y)\fC [inline]\fP"

.PP
Definition at line 22 of file Terminal\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static std::string Terminal::bold ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 92 of file Terminal\&.h\&.
.SS "static std::string Terminal::boldOff ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 101 of file Terminal\&.h\&.
.SS "static std::string Terminal::clearscr ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 54 of file Terminal\&.h\&.
.SS "static std::string Terminal::color (int colorbg, int colorfg)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 170 of file Terminal\&.h\&.
.SS "static std::string Terminal::down (int y)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 139 of file Terminal\&.h\&.
.SS "int Terminal::getHeight ()\fC [inline]\fP"

.PP
Definition at line 30 of file Terminal\&.h\&.
.SS "int Terminal::getWidth ()\fC [inline]\fP"

.PP
Definition at line 37 of file Terminal\&.h\&.
.SS "static std::string Terminal::goLoc (int x, int y)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 65 of file Terminal\&.h\&.
.SS "static std::string Terminal::left (int x)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 159 of file Terminal\&.h\&.
.SS "static std::string Terminal::reset ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 179 of file Terminal\&.h\&.
.SS "static std::string Terminal::restore ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 119 of file Terminal\&.h\&.
.SS "static std::string Terminal::right (int x)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 149 of file Terminal\&.h\&.
.SS "static std::string Terminal::save ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 110 of file Terminal\&.h\&.
.SS "void Terminal::setSize ()\fC [inline]\fP"

.PP
Definition at line 44 of file Terminal\&.h\&.
.SS "static std::string Terminal::underline ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 74 of file Terminal\&.h\&.
.SS "static std::string Terminal::underlineOff ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 83 of file Terminal\&.h\&.
.SS "static std::string Terminal::up (int y)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 129 of file Terminal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
