.TH "src/Terminal.h" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Terminal.h
.SH SYNOPSIS
.br
.PP
\fC#include <iomanip>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
