.TH "src/validation.cpp" 3 "Wed Apr 8 2020" "DOR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/validation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBnameValid\fP (std::string check)"
.br
.ti -1c
.RI "bool \fBsearchValid\fP (std::string check)"
.br
.ti -1c
.RI "bool \fBnumValid\fP (std::string check)"
.br
.ti -1c
.RI "bool \fBidValid\fP (std::string check)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool idValid (std::string check)"

.PP
Definition at line 29 of file validation\&.cpp\&.
.SS "bool nameValid (std::string check)"

.PP
Definition at line 5 of file validation\&.cpp\&.
.SS "bool numValid (std::string check)"

.PP
Definition at line 21 of file validation\&.cpp\&.
.SS "bool searchValid (std::string check)"

.PP
Definition at line 13 of file validation\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOR from the source code\&.
